# Generated by Django 5.2.4 on 2025-07-19 11:19

from django.db import migrations, models

def copy_teachers(apps, schema_editor):
    Student = apps.get_model('school', 'Student')
    StudentTeacher = Student.teachers.through

    for student in Student.objects.all():
        if student.teacher_id:
            StudentTeacher.objects.create(student_id=student.id, teacher_id=student.teacher_id)


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_group_alter_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='students', to='school.teacher'),
        ),
        migrations.RunPython(copy_teachers, reverse_code=migrations.RunPython.noop),

    ]
